Resources:
    #Security Group
    SSHSecurityGroup:
        Type: AWS::EC2::SecurityGroup
        Properties:
            GroupDescription: Allow SSH access in port 22
            SecurityGroupIngress:
            -   CidrIp: 0.0.0.0/0
                FromPort: 22
                IpProtocol: tcp
                ToPort: 22
    #EC2 Instance
    AnEC2Instance:
        Type: AWS::EC2::Instance
        Properties:
            #Select an AZ from region's AZs
            AvailabilityZone: !Select
                - 0
                - Fn::GetAZs: !Ref AWS::Region
            ImageId: ami-02a6bfdcf8224bd77
            InstanceType: t2.micro
            SecurityGroups:
                - !Ref SSHSecurityGroup

    #Elastic IP
    AnElasticIP:
        Type: AWS::EC2::EIP
        Properties:
            InstanceId: !Ref AnEC2Instance
