---
Resources:
  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: 
        Fn::Select: 
          - 0
          - Fn::GetAZs: !Ref AWS::Region
      ImageId: ami-02a6bfdcf8224bd77
      InstanceType: t2.micro
      SecurityGroups:
        - !ImportValue SecurityGroupSSH